"""
	String constants
"""

ACTION = "action"
BASE = "base"
BODY_FORMAT = "{{\"body\": \"{}\"}}"
COMMENT_MADE_MESSAGE = "Comment made for username={} userID={} comment-url={} contributorList={}"
COMMENT_NOT_MADE_MESSAGE = "Comment was not made for username={} userId={} comment-url={} contributorList={}"
COMMENTS = "comments"
DONE = "done"
HREF = "href"
ID = "id"
LINKS = "_links"
LOGIN = "login"
MAIN = "__main__"
NAME = "name"
OPENED = "opened"
OWNER = "owner"
PORT = "PORT"
PULL_REQUEST = "pull_request"
REPO = "repo"
USER = "user"